export const getUsersData = () => {
  const data = localStorage.getItem("usersData");
  return data ? JSON.parse(data) : usersData;
};

export const addNewUser = (newUser) => {
  const data = getUsersData();
  data.push(newUser);
  localStorage.setItem("usersData", JSON.stringify(data));
};

export const categories = [
  "realEstateDocuments",
  "notifications",
  "tasks",
  "delivery",
  "hours",
  "reservations",
  "lease",
  "facilities",
  "policies",
  "measurements",
  "purchases",
  "suppliers",
  "portfolio",
  "contractDocuments",
  "inventories",
  "lendingPool",
];

export const usersData = [
  {
    userId: 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    gender: 'male',
    nationality: 'American',
    password: 'password123',
    numberOfProperties: 3,
    properties: [
      {
        propertyId: 1,
        propertyName: 'Cozy Apartment',
        address: '123 Main Street',
        city: 'Amsterdam',
        state: 'NH',
        country: 'Netherlands',
        postalCode: '1001 AB',
        propertyType: 'Apartment',
        size: 800,
        numRooms: 2,
        numBathrooms: 1,
        price: 300000,
        description: 'A cozy apartment in the heart of Amsterdam.',
        yearBuilt: 2010,
        amenities: ['balcony'],
        photos: [
          'https://res.cloudinary.com/dtb1hpuil/image/upload/v1720385660/digital-marketing-agency-ntwrk-g39p1kDjvSY-unsplash_fwajrn.jpg',
        ],
        listingDate: '2023-01-15',
        lastRenovationDate: '2022-12-01',
        status: 'available',
        realEstateDocuments: [
          {
            title: 'Deed',
            documentType: 'Legal',
            documentUrl: 'https://example.com/deed.pdf',
            uploadDate: '2023-01-10',
            expiryDate: '2025-01-10',
          },
          {
            title: 'Insurance Policy',
            documentType: 'Insurance',
            documentUrl: 'https://example.com/insurance.pdf',
            uploadDate: '2023-01-10',
            expiryDate: '2024-01-10',
          },
          {
            title: 'Energy Certificate',
            documentType: 'Energy',
            documentUrl: 'https://example.com/energy_certificate.pdf',
            uploadDate: '2023-01-12',
            expiryDate: '2026-01-12',
          },
        ],
        notifications: [
          {
            notificationType: 'Maintenance',
            message: 'Scheduled maintenance for plumbing on July 5th, 2023.',
            notificationDate: '2023-06-28T09:00:00Z',
            status: 'pending',
            assignedTo: 'Facility Services',
            priority: 'High',
          },
          {
            notificationType: 'Payment Due',
            message: 'Monthly rent payment due on July 15th, 2023.',
            notificationDate: '2023-07-01T12:00:00Z',
            status: 'pending',
            assignedTo: 'Accounting Department',
            priority: 'Medium',
          },
          {
            notificationType: 'Inspection',
            message: 'Annual property inspection on August 1st, 2023.',
            notificationDate: '2023-07-20T08:00:00Z',
            status: 'scheduled',
            assignedTo: 'Inspection Team',
            priority: 'Low',
          },
        ],
        tasks: [
          {
            taskName: 'Arrange Housekeeping',
            taskDescription: 'Schedule weekly housekeeping service.',
            assignedTo: 'Housekeeping Services Inc.',
            dueDate: '2023-06-30',
            taskStatus: 'pending',
            priority: 'Low',
          },
          {
            taskName: 'Garden Maintenance',
            taskDescription: 'Water the plants and trim hedges.',
            assignedTo: 'Green Thumb Landscaping',
            dueDate: '2023-07-05',
            taskStatus: 'pending',
            priority: 'Medium',
          },
          {
            taskName: 'Repair Light Fixtures',
            taskDescription: 'Fix broken light fixtures in the hallway.',
            assignedTo: 'Electricians Inc.',
            dueDate: '2023-07-10',
            taskStatus: 'completed',
            priority: 'High',
          },
        ],
        delivery: [
          {
            deliveryDate: '2023-07-10',
            deliveryStatus: 'delivered',
            deliveryItems: [
              {
                itemName: 'New Sofa',
                itemDescription: 'Leather sofa for living room.',
                quantity: 1,
                deliveryService: 'Furniture Delivery Co.',
              },
            ],
          },
        ],
        hours: [
          { date: '2023-06-30', hoursWorked: 4 },
          { date: '2023-07-01', hoursWorked: 5 },
          { date: '2023-07-02', hoursWorked: 3 },
        ],
        reservations: [
          {
            reservationDate: '2023-07-15',
            reservationTime: '10:00 AM',
            reservationStatus: 'confirmed',
            reservationType: 'Meeting',
            reservedBy: 'John Doe',
          },
          {
            reservationDate: '2023-07-20',
            reservationTime: '2:00 PM',
            reservationStatus: 'cancelled',
            reservationType: 'Maintenance',
            reservedBy: 'John Doe',
          },
        ],
        lease: [
          {
            leaseStartDate: '2023-01-01',
            leaseEndDate: '2024-01-01',
            monthlyRent: 1200,
            leaseTerms: 'One-year lease agreement.',
          },
        ],
        facilities: [
          {
            facilityName: 'Gym',
            facilityDescription: 'Shared gym access.',
            facilityStatus: 'open',
            operatingHours: '6:00 AM - 10:00 PM',
            rules: 'No loud music',
          },
        ],
        policies: [
          {
            policyName: 'Pet Policy',
            policyDescription: 'Pets allowed with additional deposit.',
            policyEffectiveDate: '2023-01-01',
          },
        ],
        measurements: [
          {
            areaSize: 800,
            roomDimensions: {
              roomName: 'Living Room',
              width: 15,
              length: 20,
            },
          },
          {
            areaSize: 180,
            roomDimensions: {
              roomName: 'Bedroom',
              width: 12,
              length: 15,
            },
          },
          {
            areaSize: 80,
            roomDimensions: {
              roomName: 'Kitchen',
              width: 8,
              length: 10,
            },
          },
        ],
        purchases: [
          {
            purchaseDate: '2023-06-20',
            purchaseAmount: 2000,
            purchaseDescription: 'New furniture for living room.',
            vendor: 'Furniture Store',
          },
          {
            purchaseDate: '2023-07-01',
            purchaseAmount: 500,
            purchaseDescription: 'New kitchen appliances.',
            vendor: 'Appliance Store',
          },
        ],
        suppliers: [
          { supplierName: 'Furniture Store', supplierContact: '123-456-7890' },
          { supplierName: 'Appliance Store', supplierContact: '098-765-4321' },
        ],
        portfolio: [
          {
            portfolioName: 'Investment Properties',
            portfolioDescription: 'Diverse portfolio of rental properties.',
            portfolioValue: 600000,
          },
        ],
        contractDocuments: [
          {
            contractName: 'Rental Agreement',
            contractType: 'Rental',
            contractUrl: 'https://example.com/rental_contract.pdf',
            effectiveDate: '2023-01-01',
            expiryDate: '2024-01-01',
          },
        ],
        inventories: [
          {
            inventoryItem: 'Bed Linens',
            inventoryQuantity: 10,
            inventoryLocation: 'Closet',
            lastUpdated: '2023-01-15',
          },
          {
            inventoryItem: 'Towels',
            inventoryQuantity: 20,
            inventoryLocation: 'Bathroom',
            lastUpdated: '2023-02-01',
          },
        ],
        lendingPool: [
          {
            poolName: 'Maintenance Fund',
            poolDescription: 'Fund for property maintenance and repairs.',
            poolValue: 5000,
            lastContributionDate: '2023-06-15',
          },
        ],
      },
      {
        propertyId: 2,
        propertyName: 'Charming House',
        address: '456 Oak Avenue',
        city: 'Rotterdam',
        state: 'ZH',
        country: 'Netherlands',
        postalCode: '3001 CD',
        propertyType: 'House',
        size: 1200,
        numRooms: 3,
        numBathrooms: 2,
        price: 450000,
        description: 'A charming house with a garden in Rotterdam.',
        yearBuilt: 2005,
        amenities: ['garden', 'garage'],
        photos: [
          'https://res.cloudinary.com/dtb1hpuil/image/upload/v1720385657/ronnie-george-9gGvNWBeOq4-unsplash_wnz8jt.jpg',
        ],
        listingDate: '2023-02-20',
        lastRenovationDate: '2023-01-10',
        status: 'available',
        realEstateDocuments: [
          {
            title: 'Title Deed',
            documentType: 'Legal',
            documentUrl: 'https://example.com/title_deed.pdf',
            uploadDate: '2023-02-01',
            expiryDate: '2026-02-01',
          },
          {
            title: 'Property Insurance',
            documentType: 'Insurance',
            documentUrl: 'https://example.com/property_insurance.pdf',
            uploadDate: '2023-02-15',
            expiryDate: '2024-02-15',
          },
          {
            title: 'Mortgage Agreement',
            documentType: 'Mortgage',
            documentUrl: 'https://example.com/mortgage_agreement.pdf',
            uploadDate: '2023-02-10',
            expiryDate: '2033-02-10',
          },
        ],
        notifications: [
          {
            notificationType: 'Maintenance',
            message: 'Scheduled maintenance for garden on July 10th, 2023.',
            notificationDate: '2023-06-28T09:00:00Z',
            status: 'pending',
            assignedTo: 'Gardening Services',
            priority: 'Medium',
          },
          {
            notificationType: 'Payment Due',
            message: 'Monthly mortgage payment due on July 20th, 2023.',
            notificationDate: '2023-07-01T12:00:00Z',
            status: 'pending',
            assignedTo: 'Finance Department',
            priority: 'High',
          },
          {
            notificationType: 'Inspection',
            message: 'Annual property inspection on August 5th, 2023.',
            notificationDate: '2023-07-25T08:00:00Z',
            status: 'scheduled',
            assignedTo: 'Inspection Team',
            priority: 'Low',
          },
        ],
        tasks: [
          {
            taskName: 'Lawn Care',
            taskDescription: 'Mow the lawn and trim bushes.',
            assignedTo: 'Green Thumb Landscaping',
            dueDate: '2023-07-05',
            taskStatus: 'pending',
            priority: 'Medium',
          },
          {
            taskName: 'Painting',
            taskDescription: 'Touch up exterior paint.',
            assignedTo: 'Local Painters Ltd.',
            dueDate: '2023-07-15',
            taskStatus: 'pending',
            priority: 'High',
          },
          {
            taskName: 'Roof Repair',
            taskDescription: 'Fix roof leaks.',
            assignedTo: 'Roofing Services Inc.',
            dueDate: '2023-07-20',
            taskStatus: 'completed',
            priority: 'High',
          },
        ],
        delivery: [
          {
            deliveryDate: '2023-07-12',
            deliveryStatus: 'delivered',
            deliveryItems: [
              {
                itemName: 'New Dining Table',
                itemDescription: 'Wooden dining table for the dining room.',
                quantity: 1,
                deliveryService: 'Furniture Delivery Co.',
              },
            ],
          },
        ],
        hours: [
          { date: '2023-06-30', hoursWorked: 6 },
          { date: '2023-07-01', hoursWorked: 4 },
          { date: '2023-07-02', hoursWorked: 5 },
        ],
        reservations: [
          {
            reservationDate: '2023-07-18',
            reservationTime: '11:00 AM',
            reservationStatus: 'confirmed',
            reservationType: 'Maintenance',
            reservedBy: 'John Doe',
          },
          {
            reservationDate: '2023-07-25',
            reservationTime: '3:00 PM',
            reservationStatus: 'cancelled',
            reservationType: 'Inspection',
            reservedBy: 'John Doe',
          },
        ],
        lease: [
          {
            leaseStartDate: '2023-03-01',
            leaseEndDate: '2024-03-01',
            monthlyRent: 1500,
            leaseTerms: 'Two-year lease agreement.',
          },
        ],
        facilities: [
          {
            facilityName: 'Garage',
            facilityDescription: 'Attached garage for one car.',
            facilityStatus: 'open',
            operatingHours: '24/7',
            rules: 'No storage of hazardous materials',
          },
        ],
        policies: [
          {
            policyName: 'Pet Policy',
            policyDescription: 'Pets allowed with additional deposit.',
            policyEffectiveDate: '2023-03-01',
          },
        ],
        measurements: [
          {
            areaSize: 800,
            roomDimensions: {
              roomName: 'Living Room',
              width: 15,
              length: 20,
            },
          },
          {
            areaSize: 180,
            roomDimensions: {
              roomName: 'Bedroom',
              width: 12,
              length: 15,
            },
          },
          {
            areaSize: 80,
            roomDimensions: {
              roomName: 'Kitchen',
              width: 8,
              length: 10,
            },
          },
        ],
        purchases: [
          {
            purchaseDate: '2023-06-25',
            purchaseAmount: 3000,
            purchaseDescription: 'New appliances for kitchen.',
            vendor: 'Appliance Store',
          },
          {
            purchaseDate: '2023-07-05',
            purchaseAmount: 1500,
            purchaseDescription: 'New garden furniture.',
            vendor: 'Garden Supplies Ltd.',
          },
        ],
        suppliers: [
          { supplierName: 'Appliance Store', supplierContact: '987-654-3210' },
          { supplierName: 'Garden Supplies Ltd.', supplierContact: '456-789-1230' },
        ],
        portfolio: [
          {
            portfolioName: 'Rental Properties',
            portfolioDescription: 'Investment portfolio of residential properties.',
            portfolioValue: 800000,
          },
        ],
        contractDocuments: [
          {
            contractName: 'Lease Agreement',
            contractType: 'Lease',
            contractUrl: 'https://example.com/lease_agreement.pdf',
            effectiveDate: '2023-03-01',
            expiryDate: '2024-03-01',
          },
        ],
        inventories: [
          {
            inventoryItem: 'Garden Tools',
            inventoryQuantity: 5,
            inventoryLocation: 'Garage',
            lastUpdated: '2023-02-20',
          },
          {
            inventoryItem: 'Kitchen Utensils',
            inventoryQuantity: 20,
            inventoryLocation: 'Kitchen',
            lastUpdated: '2023-03-10',
          },
        ],
        lendingPool: [
          {
            poolName: 'Maintenance Fund',
            poolDescription: 'Fund for property maintenance and repairs.',
            poolValue: 7000,
            lastContributionDate: '2023-06-20',
          },
        ],
      },
      {
        propertyId: 3,
        propertyName: 'Modern Loft',
        address: '789 Park Lane',
        city: 'Amsterdam',
        state: 'NH',
        country: 'Netherlands',
        postalCode: '1002 CD',
        propertyType: 'Loft',
        size: 1000,
        numRooms: 1,
        numBathrooms: 1,
        price: 400000,
        description: 'A modern loft with minimalist design.',
        yearBuilt: 2015,
        amenities: ['rooftop terrace', 'gym'],
        photos: [
          'https://res.cloudinary.com/dtb1hpuil/image/upload/v1720385655/brian-babb-XbwHrt87mQ0-unsplash_e2m8ed.jpg',
        ],
        listingDate: '2023-03-10',
        lastRenovationDate: '2023-02-01',
        status: 'available',
        realEstateDocuments: [
          {
            title: 'Title Deed',
            documentType: 'Legal',
            documentUrl: 'https://example.com/title_deed.pdf',
            uploadDate: '2023-03-01',
            expiryDate: '2026-03-01',
          },
          {
            title: 'Property Insurance',
            documentType: 'Insurance',
            documentUrl: 'https://example.com/property_insurance.pdf',
            uploadDate: '2023-03-15',
            expiryDate: '2024-03-15',
          },
          {
            title: 'Renovation Contract',
            documentType: 'Renovation',
            documentUrl: 'https://example.com/renovation_contract.pdf',
            uploadDate: '2023-03-05',
            expiryDate: '2024-03-05',
          },
        ],
        notifications: [
          {
            notificationType: 'Maintenance',
            message: 'Scheduled maintenance for HVAC system on July 8th, 2023.',
            notificationDate: '2023-06-28T09:00:00Z',
            status: 'pending',
            assignedTo: 'HVAC Services',
            priority: 'High',
          },
          {
            notificationType: 'Payment Due',
            message: 'Monthly HOA fee due on July 10th, 2023.',
            notificationDate: '2023-07-01T12:00:00Z',
            status: 'pending',
            assignedTo: 'HOA Management',
            priority: 'Medium',
          },
          {
            notificationType: 'Inspection',
            message: 'Annual property inspection on August 10th, 2023.',
            notificationDate: '2023-07-30T08:00:00Z',
            status: 'scheduled',
            assignedTo: 'Inspection Team',
            priority: 'Low',
          },
        ],
        tasks: [
          {
            taskName: 'Roof Maintenance',
            taskDescription: 'Inspect and clean rooftop terrace.',
            assignedTo: 'Maintenance Services Ltd.',
            dueDate: '2023-07-05',
            taskStatus: 'pending',
            priority: 'Low',
          },
          {
            taskName: 'Fitness Equipment Check',
            taskDescription: 'Inspect gym equipment and schedule maintenance.',
            assignedTo: 'Fitness Equipment Services',
            dueDate: '2023-07-10',
            taskStatus: 'pending',
            priority: 'Medium',
          },
          {
            taskName: 'Paint Walls',
            taskDescription: 'Repaint interior walls.',
            assignedTo: 'Painters Inc.',
            dueDate: '2023-07-15',
            taskStatus: 'completed',
            priority: 'High',
          },
        ],
        delivery: [
          {
            deliveryDate: '2023-07-15',
            deliveryStatus: 'delivered',
            deliveryItems: [
              {
                itemName: 'New Bed',
                itemDescription: 'Queen size bed for the bedroom.',
                quantity: 1,
                deliveryService: 'Furniture Delivery Co.',
              },
            ],
          },
        ],
        hours: [
          { date: '2023-06-30', hoursWorked: 3 },
          { date: '2023-07-01', hoursWorked: 4 },
          { date: '2023-07-02', hoursWorked: 5 },
        ],
        reservations: [
          {
            reservationDate: '2023-07-20',
            reservationTime: '2:00 PM',
            reservationStatus: 'confirmed',
            reservationType: 'Meeting',
            reservedBy: 'John Doe',
          },
          {
            reservationDate: '2023-07-25',
            reservationTime: '4:00 PM',
            reservationStatus: 'cancelled',
            reservationType: 'Inspection',
            reservedBy: 'John Doe',
          },
        ],
        lease: [
          {
            leaseStartDate: '2023-02-01',
            leaseEndDate: '2024-02-01',
            monthlyRent: 1800,
            leaseTerms: 'Two-year lease agreement.',
          },
        ],
        facilities: [
          {
            facilityName: 'Rooftop Terrace',
            facilityDescription: 'Private rooftop terrace with city views.',
            facilityStatus: 'open',
            operatingHours: '6:00 AM - 10:00 PM',
            rules: 'No parties after 10 PM',
          },
        ],
        policies: [
          {
            policyName: 'Pet Policy',
            policyDescription: 'Pets allowed with additional deposit.',
            policyEffectiveDate: '2023-02-01',
          },
        ],
        measurements: [
          {
            areaSize: 1000,
            roomDimensions: {
              roomName: 'Living Room',
              width: 20,
              length: 25,
            },
          },
          {
            areaSize: 180,
            roomDimensions: {
              roomName: 'Bedroom',
              width: 12,
              length: 15,
            },
          },
          {
            areaSize: 120,
            roomDimensions: {
              roomName: 'Kitchen',
              width: 12,
              length: 10,
            },
          },
        ],
        purchases: [
          {
            purchaseDate: '2023-06-18',
            purchaseAmount: 2500,
            purchaseDescription: 'New furniture for living room.',
            vendor: 'Furniture World',
          },
          {
            purchaseDate: '2023-07-05',
            purchaseAmount: 800,
            purchaseDescription: 'New lighting fixtures.',
            vendor: 'Lighting Store',
          },
        ],
        suppliers: [
          { supplierName: 'Furniture World', supplierContact: '123-456-7890' },
          { supplierName: 'Lighting Store', supplierContact: '555-987-6543' },
        ],
        portfolio: [
          {
            portfolioName: 'Rental Investments',
            portfolioDescription: 'Portfolio of high-end rental properties.',
            portfolioValue: 900000,
          },
        ],
        contractDocuments: [
          {
            contractName: 'HOA Agreement',
            contractType: 'HOA',
            contractUrl: 'https://example.com/hoa_agreement.pdf',
            effectiveDate: '2023-02-01',
            expiryDate: '2024-02-01',
          },
        ],
        inventories: [
          {
            inventoryItem: 'Fitness Equipment',
            inventoryQuantity: 3,
            inventoryLocation: 'Gym',
            lastUpdated: '2023-03-10',
          },
          {
            inventoryItem: 'Kitchen Appliances',
            inventoryQuantity: 10,
            inventoryLocation: 'Kitchen',
            lastUpdated: '2023-04-15',
          },
        ],
        lendingPool: [
          {
            poolName: 'Property Improvement Fund',
            poolDescription: 'Fund for loft upgrades and maintenance.',
            poolValue: 7000,
            lastContributionDate: '2023-06-25',
          },
        ],
      },
    ],
  },
  {
    userId: 2,
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@example.com',
    gender: 'female',
    nationality: 'British',
    password: 'securepassword',
    numberOfProperties: 2,
    properties: [
      {
        propertyId: 4,
        propertyName: 'Luxurious Condo',
        address: '101 Riverside Drive',
        city: 'Amsterdam',
        state: 'NH',
        country: 'Netherlands',
        postalCode: '1003 AB',
        propertyType: 'Condo',
        size: 1500,
        numRooms: 3,
        numBathrooms: 2,
        price: 550000,
        description: 'A luxurious condo with a stunning river view.',
        yearBuilt: 2018,
        amenities: ['pool', 'gym'],
        photos: [
          'https://res.cloudinary.com/dtb1hpuil/image/upload/v1720385660/digital-marketing-agency-ntwrk-g39p1kDjvSY-unsplash_fwajrn.jpg',
        ],
        listingDate: '2023-02-15',
        lastRenovationDate: '2023-01-01',
        status: 'available',
        realEstateDocuments: [
          {
            title: 'Title Deed',
            documentType: 'Legal',
            documentUrl: 'https://example.com/title_deed.pdf',
            uploadDate: '2023-02-10',
            expiryDate: '2028-02-10',
          },
          {
            title: 'Insurance Policy',
            documentType: 'Insurance',
            documentUrl: 'https://example.com/insurance.pdf',
            uploadDate: '2023-02-15',
            expiryDate: '2024-02-15',
          },
        ],
        notifications: [
          {
            notificationType: 'Maintenance',
            message: 'Scheduled maintenance for pool on July 15th, 2023.',
            notificationDate: '2023-06-30T09:00:00Z',
            status: 'pending',
            assignedTo: 'Pool Services',
            priority: 'High',
          },
          {
            notificationType: 'Payment Due',
            message: 'Monthly condo fee due on July 20th, 2023.',
            notificationDate: '2023-07-01T12:00:00Z',
            status: 'pending',
            assignedTo: 'HOA Management',
            priority: 'Medium',
          },
          {
            notificationType: 'Inspection',
            message: 'Annual property inspection on August 5th, 2023.',
            notificationDate: '2023-07-25T08:00:00Z',
            status: 'scheduled',
            assignedTo: 'Inspection Team',
            priority: 'Low',
          },
          {
            notificationType: 'Security Update',
            message: 'New security system installation on July 25th, 2023.',
            notificationDate: '2023-07-10T08:00:00Z',
            status: 'pending',
            assignedTo: 'Security Services',
            priority: 'High',
          },
          {
            notificationType: 'Utilities Maintenance',
            message: 'Electrical maintenance on August 1st, 2023.',
            notificationDate: '2023-07-20T08:00:00Z',
            status: 'pending',
            assignedTo: 'Utility Services',
            priority: 'Medium',
          },
          {
            notificationType: 'Pest Control',
            message: 'Pest control service on August 10th, 2023.',
            notificationDate: '2023-07-25T08:00:00Z',
            status: 'scheduled',
            assignedTo: 'Pest Control Inc.',
            priority: 'Low',
          },
          {
            notificationType: 'Landscape Maintenance',
            message: 'Gardening services on July 30th, 2023.',
            notificationDate: '2023-07-20T08:00:00Z',
            status: 'pending',
            assignedTo: 'Gardening Services',
            priority: 'Medium',
          },
        ],
        tasks: [
          {
            taskName: 'Pool Cleaning',
            taskDescription: 'Clean the pool weekly.',
            assignedTo: 'Pool Services Inc.',
            dueDate: '2023-07-10',
            taskStatus: 'pending',
            priority: 'High',
          },
          {
            taskName: 'Window Cleaning',
            taskDescription: 'Clean windows inside and out.',
            assignedTo: 'Cleaning Services Ltd.',
            dueDate: '2023-07-15',
            taskStatus: 'pending',
            priority: 'Medium',
          },
          {
            taskName: 'HVAC Maintenance',
            taskDescription: 'Check and service HVAC system.',
            assignedTo: 'HVAC Specialists',
            dueDate: '2023-07-20',
            taskStatus: 'pending',
            priority: 'High',
          },
          {
            taskName: 'Paint Walls',
            taskDescription: 'Repaint interior walls.',
            assignedTo: 'Painters Inc.',
            dueDate: '2023-07-25',
            taskStatus: 'completed',
            priority: 'Medium',
          },
          {
            taskName: 'Carpet Cleaning',
            taskDescription: 'Deep clean all carpets.',
            assignedTo: 'Cleaning Services Ltd.',
            dueDate: '2023-07-30',
            taskStatus: 'pending',
            priority: 'Low',
          },
          {
            taskName: 'Furniture Assembly',
            taskDescription: 'Assemble new furniture in living room.',
            assignedTo: 'Furniture Assembly Co.',
            dueDate: '2023-08-01',
            taskStatus: 'pending',
            priority: 'Low',
          },
          {
            taskName: 'Roof Inspection',
            taskDescription: 'Inspect and repair roof.',
            assignedTo: 'Roofing Services Inc.',
            dueDate: '2023-08-05',
            taskStatus: 'pending',
            priority: 'High',
          },
        ],
        delivery: [
          {
            deliveryDate: '2023-07-12',
            deliveryStatus: 'delivered',
            deliveryItems: [
              {
                itemName: 'New Dining Table',
                itemDescription: 'Glass dining table for dining room.',
                quantity: 1,
                deliveryService: 'Furniture Delivery Co.',
              },
            ],
          },
        ],
        hours: [
          { date: '2023-06-30', hoursWorked: 6 },
          { date: '2023-07-01', hoursWorked: 4 },
          { date: '2023-07-02', hoursWorked: 5 },
          { date: '2023-07-03', hoursWorked: 6 },
        ],
        reservations: [
          {
            reservationDate: '2023-07-20',
            reservationTime: '2:00 PM',
            reservationStatus: 'confirmed',
            reservationType: 'Meeting',
            reservedBy: 'Alice Smith',
          },
        ],
        lease: [
          {
            leaseStartDate: '2023-03-01',
            leaseEndDate: '2024-03-01',
            monthlyRent: 2000,
            leaseTerms: 'One-year lease agreement.',
          },
        ],
        facilities: [
          {
            facilityName: 'Pool',
            facilityDescription: 'Outdoor swimming pool.',
            facilityStatus: 'open',
            operatingHours: '6:00 AM - 9:00 PM',
            rules: 'No diving',
          },
          {
            facilityName: 'Gym',
            facilityDescription: 'Fully equipped gym.',
            facilityStatus: 'open',
            operatingHours: '24/7',
            rules: 'No food or drinks',
          },
          {
            facilityName: 'Sauna',
            facilityDescription: 'Relaxing sauna room.',
            facilityStatus: 'open',
            operatingHours: '8:00 AM - 10:00 PM',
            rules: 'No loud music',
          },
          {
            facilityName: 'Conference Room',
            facilityDescription: 'Business conference room.',
            facilityStatus: 'open',
            operatingHours: '8:00 AM - 8:00 PM',
            rules: 'Booking required',
          },
          {
            facilityName: 'Parking Garage',
            facilityDescription: 'Underground parking garage.',
            facilityStatus: 'open',
            operatingHours: '24/7',
            rules: 'No overnight parking',
          },
          {
            facilityName: 'Rooftop Terrace',
            facilityDescription: 'Terrace with city views.',
            facilityStatus: 'open',
            operatingHours: '6:00 AM - 10:00 PM',
            rules: 'No parties after 10 PM',
          },
        ],
        policies: [
          {
            policyName: 'Pet Policy',
            policyDescription: 'Pets allowed with additional deposit.',
            policyEffectiveDate: '2023-03-01',
          },
        ],
        measurements: [
          {
            areaSize: 1500,
            roomDimensions: {
              roomName: 'Living Room',
              width: 20,
              length: 25,
            },
          },
          {
            areaSize: 270,
            roomDimensions: {
              roomName: 'Bedroom 1',
              width: 15,
              length: 18,
            },
          },
          {
            areaSize: 180,
            roomDimensions: {
              roomName: 'Bedroom 2',
              width: 12,
              length: 15,
            },
          },
          {
            areaSize: 120,
            roomDimensions: {
              roomName: 'Kitchen',
              width: 10,
              length: 12,
            },
          },
        ],
        purchases: [
          {
            purchaseDate: '2023-06-25',
            purchaseAmount: 3000,
            purchaseDescription: 'New appliances for kitchen.',
            vendor: 'Appliance Store',
          },
          {
            purchaseDate: '2023-07-05',
            purchaseAmount: 1500,
            purchaseDescription: 'New garden furniture.',
            vendor: 'Garden Supplies Ltd.',
          },
          {
            purchaseDate: '2023-07-10',
            purchaseAmount: 2500,
            purchaseDescription: 'New living room furniture.',
            vendor: 'Furniture Store',
          },
          {
            purchaseDate: '2023-07-15',
            purchaseAmount: 500,
            purchaseDescription: 'New lighting fixtures.',
            vendor: 'Lighting Store',
          },
          {
            purchaseDate: '2023-07-20',
            purchaseAmount: 800,
            purchaseDescription: 'New bathroom accessories.',
            vendor: 'Home Decor Shop',
          },
        ],
        suppliers: [
          { supplierName: 'Appliance Store', supplierContact: '987-654-3210' },
          { supplierName: 'Garden Supplies Ltd.', supplierContact: '456-789-1230' },
          { supplierName: 'Furniture Store', supplierContact: '123-456-7890' },
          { supplierName: 'Lighting Store', supplierContact: '555-987-6543' },
          { supplierName: 'Home Decor Shop', supplierContact: '444-555-6666' },
        ],
        portfolio: [
          {
            portfolioName: 'Luxury Properties',
            portfolioDescription: 'Portfolio of high-end properties.',
            portfolioValue: 1200000,
          },
        ],
        contractDocuments: [
          {
            contractName: 'Lease Agreement',
            contractType: 'Lease',
            contractUrl: 'https://example.com/lease_agreement.pdf',
            effectiveDate: '2023-03-01',
            expiryDate: '2024-03-01',
          },
          {
            contractName: 'Maintenance Contract',
            contractType: 'Maintenance',
            contractUrl: 'https://example.com/maintenance_contract.pdf',
            effectiveDate: '2023-03-01',
            expiryDate: '2024-03-01',
          },
        ],
        inventories: [
          {
            inventoryItem: 'Kitchen Utensils',
            inventoryQuantity: 50,
            inventoryLocation: 'Kitchen',
            lastUpdated: '2023-03-10',
          },
          {
            inventoryItem: 'Bed Linens',
            inventoryQuantity: 30,
            inventoryLocation: 'Closet',
            lastUpdated: '2023-04-01',
          },
          {
            inventoryItem: 'Towels',
            inventoryQuantity: 40,
            inventoryLocation: 'Bathroom',
            lastUpdated: '2023-05-01',
          },
          {
            inventoryItem: 'Garden Tools',
            inventoryQuantity: 10,
            inventoryLocation: 'Garage',
            lastUpdated: '2023-06-01',
          },
          {
            inventoryItem: 'Office Supplies',
            inventoryQuantity: 20,
            inventoryLocation: 'Office',
            lastUpdated: '2023-06-15',
          },
        ],
        lendingPool: [
          {
            poolName: 'Property Maintenance Fund',
            poolDescription: 'Fund for ongoing property maintenance.',
            poolValue: 10000,
            lastContributionDate: '2023-06-20',
          },
        ],
      },
      {
        propertyId: 5,
        propertyName: 'Spacious Villa',
        address: '202 Green Park',
        city: 'Rotterdam',
        state: 'ZH',
        country: 'Netherlands',
        postalCode: '3012 AB',
        propertyType: 'Villa',
        size: 2500,
        numRooms: 5,
        numBathrooms: 3,
        price: 850000,
        description: 'A spacious villa with a large garden in the nature.',
        yearBuilt: 2010,
        amenities: ['garden', 'garage', 'pool'],
        photos: [
          'https://res.cloudinary.com/dtb1hpuil/image/upload/v1720385657/ronnie-george-9gGvNWBeOq4-unsplash_wnz8jt.jpg',
        ],
        listingDate: '2023-04-10',
        lastRenovationDate: '2023-03-01',
        status: 'available',
        realEstateDocuments: [
          {
            title: 'Title Deed',
            documentType: 'Legal',
            documentUrl: 'https://example.com/title_deed.pdf',
            uploadDate: '2023-04-05',
            expiryDate: '2029-04-05',
          },
          {
            title: 'Insurance Policy',
            documentType: 'Insurance',
            documentUrl: 'https://example.com/insurance.pdf',
            uploadDate: '2023-04-10',
            expiryDate: '2024-04-10',
          },
        ],
        notifications: [
          {
            notificationType: 'Maintenance',
            message: 'Scheduled maintenance for pool on July 18th, 2023.',
            notificationDate: '2023-06-28T09:00:00Z',
            status: 'pending',
            assignedTo: 'Pool Services',
            priority: 'High',
          },
          {
            notificationType: 'Payment Due',
            message: 'Monthly villa fee due on July 25th, 2023.',
            notificationDate: '2023-07-01T12:00:00Z',
            status: 'pending',
            assignedTo: 'HOA Management',
            priority: 'Medium',
          },
          {
            notificationType: 'Inspection',
            message: 'Annual property inspection on August 8th, 2023.',
            notificationDate: '2023-07-20T08:00:00Z',
            status: 'scheduled',
            assignedTo: 'Inspection Team',
            priority: 'Low',
          },
          {
            notificationType: 'Security Update',
            message: 'New security system installation on July 28th, 2023.',
            notificationDate: '2023-07-10T08:00:00Z',
            status: 'pending',
            assignedTo: 'Security Services',
            priority: 'High',
          },
          {
            notificationType: 'Utilities Maintenance',
            message: 'Electrical maintenance on August 5th, 2023.',
            notificationDate: '2023-07-20T08:00:00Z',
            status: 'pending',
            assignedTo: 'Utility Services',
            priority: 'Medium',
          },
          {
            notificationType: 'Pest Control',
            message: 'Pest control service on August 12th, 2023.',
            notificationDate: '2023-07-25T08:00:00Z',
            status: 'scheduled',
            assignedTo: 'Pest Control Inc.',
            priority: 'Low',
          },
          {
            notificationType: 'Landscape Maintenance',
            message: 'Gardening services on July 25th, 2023.',
            notificationDate: '2023-07-15T08:00:00Z',
            status: 'pending',
            assignedTo: 'Gardening Services',
            priority: 'Medium',
          },
        ],
        tasks: [
          {
            taskName: 'Pool Cleaning',
            taskDescription: 'Clean the pool weekly.',
            assignedTo: 'Pool Services Inc.',
            dueDate: '2023-07-12',
            taskStatus: 'pending',
            priority: 'High',
          },
          {
            taskName: 'Window Cleaning',
            taskDescription: 'Clean windows inside and out.',
            assignedTo: 'Cleaning Services Ltd.',
            dueDate: '2023-07-18',
            taskStatus: 'pending',
            priority: 'Medium',
          },
          {
            taskName: 'HVAC Maintenance',
            taskDescription: 'Check and service HVAC system.',
            assignedTo: 'HVAC Specialists',
            dueDate: '2023-07-22',
            taskStatus: 'pending',
            priority: 'High',
          },
          {
            taskName: 'Paint Walls',
            taskDescription: 'Repaint interior walls.',
            assignedTo: 'Painters Inc.',
            dueDate: '2023-07-26',
            taskStatus: 'completed',
            priority: 'Medium',
          },
          {
            taskName: 'Carpet Cleaning',
            taskDescription: 'Deep clean all carpets.',
            assignedTo: 'Cleaning Services Ltd.',
            dueDate: '2023-07-30',
            taskStatus: 'pending',
            priority: 'Low',
          },
          {
            taskName: 'Furniture Assembly',
            taskDescription: 'Assemble new furniture in living room.',
            assignedTo: 'Furniture Assembly Co.',
            dueDate: '2023-08-01',
            taskStatus: 'pending',
            priority: 'Low',
          },
          {
            taskName: 'Roof Inspection',
            taskDescription: 'Inspect and repair roof.',
            assignedTo: 'Roofing Services Inc.',
            dueDate: '2023-08-08',
            taskStatus: 'pending',
            priority: 'High',
          },
          {
            taskName: 'Garden Maintenance',
            taskDescription: 'Water the plants and trim hedges.',
            assignedTo: 'Green Thumb Landscaping',
            dueDate: '2023-07-05',
            taskStatus: 'pending',
            priority: 'Medium',
          },
          {
            taskName: 'Repair Light Fixtures',
            taskDescription: 'Fix broken light fixtures in the hallway.',
            assignedTo: 'Electricians Inc.',
            dueDate: '2023-07-10',
            taskStatus: 'completed',
            priority: 'High',
          },
        ],
        delivery: [
          {
            deliveryDate: '2023-07-20',
            deliveryStatus: 'delivered',
            deliveryItems: [
              {
                itemName: 'New Sofa',
                itemDescription: 'Leather sofa for living room.',
                quantity: 1,
                deliveryService: 'Furniture Delivery Co.',
              },
            ],
          },
        ],
        hours: [
          { date: '2023-06-30', hoursWorked: 7 },
          { date: '2023-07-01', hoursWorked: 5 },
          { date: '2023-07-02', hoursWorked: 6 },
          { date: '2023-07-03', hoursWorked: 7 },
        ],
        reservations: [
          {
            reservationDate: '2023-07-25',
            reservationTime: '3:00 PM',
            reservationStatus: 'confirmed',
            reservationType: 'Maintenance',
            reservedBy: 'Alice Smith',
          },
        ],
        lease: [
          {
            leaseStartDate: '2023-04-01',
            leaseEndDate: '2024-04-01',
            monthlyRent: 2500,
            leaseTerms: 'One-year lease agreement.',
          },
        ],
        facilities: [
          {
            facilityName: 'Pool',
            facilityDescription: 'Outdoor swimming pool.',
            facilityStatus: 'open',
            operatingHours: '6:00 AM - 9:00 PM',
            rules: 'No diving',
          },
          {
            facilityName: 'Gym',
            facilityDescription: 'Fully equipped gym.',
            facilityStatus: 'open',
            operatingHours: '24/7',
            rules: 'No food or drinks',
          },
          {
            facilityName: 'Sauna',
            facilityDescription: 'Relaxing sauna room.',
            facilityStatus: 'open',
            operatingHours: '8:00 AM - 10:00 PM',
            rules: 'No loud music',
          },
          {
            facilityName: 'Conference Room',
            facilityDescription: 'Business conference room.',
            facilityStatus: 'open',
            operatingHours: '8:00 AM - 8:00 PM',
            rules: 'Booking required',
          },
          {
            facilityName: 'Parking Garage',
            facilityDescription: 'Underground parking garage.',
            facilityStatus: 'open',
            operatingHours: '24/7',
            rules: 'No overnight parking',
          },
          {
            facilityName: 'Rooftop Terrace',
            facilityDescription: 'Terrace with city views.',
            facilityStatus: 'open',
            operatingHours: '6:00 AM - 10:00 PM',
            rules: 'No parties after 10 PM',
          },
        ],
        policies: [
          {
            policyName: 'Pet Policy',
            policyDescription: 'Pets allowed with additional deposit.',
            policyEffectiveDate: '2023-04-01',
          },
        ],
        measurements: [
          {
            areaSize: 2500,
            roomDimensions: {
              roomName: 'Living Room',
              width: 25,
              length: 30,
            },
          },
          {
            areaSize: 360,
            roomDimensions: {
              roomName: 'Bedroom 1',
              width: 18,
              length: 20,
            },
          },
          {
            areaSize: 288,
            roomDimensions: {
              roomName: 'Bedroom 2',
              width: 16,
              length: 18,
            },
          },
          {
            areaSize: 270,
            roomDimensions: {
              roomName: 'Bedroom 3',
              width: 15,
              length: 18,
            },
          },
          {
            areaSize: 270,
            roomDimensions: {
              roomName: 'Kitchen',
              width: 15,
              length: 18,
            },
          },
        ],
        purchases: [
          {
            purchaseDate: '2023-07-01',
            purchaseAmount: 4500,
            purchaseDescription: 'New kitchen appliances.',
            vendor: 'Appliance Store',
          },
          {
            purchaseDate: '2023-07-10',
            purchaseAmount: 3500,
            purchaseDescription: 'New garden furniture.',
            vendor: 'Garden Supplies Ltd.',
          },
          {
            purchaseDate: '2023-07-20',
            purchaseAmount: 3000,
            purchaseDescription: 'New living room furniture.',
            vendor: 'Furniture Store',
          },
          {
            purchaseDate: '2023-07-30',
            purchaseAmount: 800,
            purchaseDescription: 'New lighting fixtures.',
            vendor: 'Lighting Store',
          },
          {
            purchaseDate: '2023-08-01',
            purchaseAmount: 1200,
            purchaseDescription: 'New bathroom accessories.',
            vendor: 'Home Decor Shop',
          },
          {
            purchaseDate: '2023-08-05',
            purchaseAmount: 1500,
            purchaseDescription: 'New bedroom furniture.',
            vendor: 'Furniture World',
          },
          {
            purchaseDate: '2023-08-10',
            purchaseAmount: 700,
            purchaseDescription: 'New office desk.',
            vendor: 'Office Supplies Ltd.',
          },
        ],
        suppliers: [
          { supplierName: 'Appliance Store', supplierContact: '987-654-3210' },
          { supplierName: 'Garden Supplies Ltd.', supplierContact: '456-789-1230' },
          { supplierName: 'Furniture Store', supplierContact: '123-456-7890' },
          { supplierName: 'Lighting Store', supplierContact: '555-987-6543' },
          { supplierName: 'Home Decor Shop', supplierContact: '444-555-6666' },
          { supplierName: 'Furniture World', supplierContact: '333-444-5555' },
          { supplierName: 'Office Supplies Ltd.', supplierContact: '222-333-4444' },
        ],
        portfolio: [
          {
            portfolioName: 'Luxury Villas',
            portfolioDescription: 'Portfolio of high-end villas.',
            portfolioValue: 1600000,
          },
        ],
        contractDocuments: [
          {
            contractName: 'Lease Agreement',
            contractType: 'Lease',
            contractUrl: 'https://example.com/lease_agreement.pdf',
            effectiveDate: '2023-04-01',
            expiryDate: '2024-04-01',
          },
          {
            contractName: 'Maintenance Contract',
            contractType: 'Maintenance',
            contractUrl: 'https://example.com/maintenance_contract.pdf',
            effectiveDate: '2023-04-01',
            expiryDate: '2024-04-01',
          },
        ],
        inventories: [
          {
            inventoryItem: 'Kitchen Utensils',
            inventoryQuantity: 50,
            inventoryLocation: 'Kitchen',
            lastUpdated: '2023-04-10',
          },
          {
            inventoryItem: 'Bed Linens',
            inventoryQuantity: 40,
            inventoryLocation: 'Closet',
            lastUpdated: '2023-04-20',
          },
          {
            inventoryItem: 'Towels',
            inventoryQuantity: 30,
            inventoryLocation: 'Bathroom',
            lastUpdated: '2023-05-10',
          },
          {
            inventoryItem: 'Garden Tools',
            inventoryQuantity: 20,
            inventoryLocation: 'Garage',
            lastUpdated: '2023-06-05',
          },
          {
            inventoryItem: 'Office Supplies',
            inventoryQuantity: 15,
            inventoryLocation: 'Office',
            lastUpdated: '2023-06-20',
          },
        ],
        lendingPool: [
          {
            poolName: 'Villa Maintenance Fund',
            poolDescription: 'Fund for villa maintenance and repairs.',
            poolValue: 15000,
            lastContributionDate: '2023-07-01',
          },
        ],
      },
    ],
  },
];

